services:
  postgres:
    image: postgres:latest
    container_name: order-platform
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: order-platform-db
    volumes:
      - order-platform-db:/var/lib/postgresql

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq-order-platform
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-order-platform_data:/var/lib/rabbitmq
      - rabbitmq-order-platform_log:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  order-platform-db:
  rabbitmq-order-platform_data:
  rabbitmq-order-platform_log: