# OPEN API CONFIG
springdoc.swagger-ui.path=/api-docs.html
springdoc.api-docs.path=/api-docs
springdoc.packages-to-scan=com.cauanlagrotta.order_platform_challange

# RABBITMQ CONFIG
spring.rabbitmq.host=localhost
spring.rabbitmq.username=root
spring.rabbitmq.password=root
spring.rabbitmq.port=5672

order.created.queue=ORDER_CREATED_QUEUE
order.confirmed.queue=ORDER_CONFIRMED_QUEUE
order.failed.queue=ORDER_FAILED_QUEUE

order.created.bind=ORDER_CREATED_BIND
order.confirmed.bind=ORDER_CREATED_BIND
order.failed.bind=ORDER_CREATED_BIND

# POSTGRESQL CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/order-platform-db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server CONFIG
server.port=8080